GET http://localhost:3002/api/v1/user/63cbdc062e080973f51245d5 HTTP/1.1
Content-Type: application/json

###

PATCH http://localhost:3002/api/v1/user/63cc27857b3304d0f7183f17 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lZGljMTExMSIsImlhdCI6MTY3NDMzMzE5MSwiZXhwIjoxNjc0MzM2NzkxfQ.1usTR9k_4HSQRhYmXqEqir5WwUEHIsWj8jCiLZew47E

{
  "allergies": ["Pollen"],
  "medications": ["Vitamins"],
  "medical_history": ["Asthma"]
}