GET http://localhost:3002/api/v1/user/63cbdc062e080973f51245d5 HTTP/1.1
Content-Type: application/json

###

PATCH http://localhost:3002/api/v1/user/63cbefbf11665e0ad9e29065 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZpcnN0dXNlcjIyIiwiaWF0IjoxNjc0MzIzMzE1LCJleHAiOjE2NzQzMjY5MTV9.GdIdByrCJAxd_pXRa2Zw7b6d-alMSOfJj6-CBvOBU64

{
  "allergies": ["none"]
}